export const AppConfig = {
  VERSION: "4.24.10.31.07",
  ADMIN_API_URL: process.env.REACT_APP_VARIAMOS_ADMIN_API_URL || "",
  LANGUAGES_API_URL: process.env.REACT_APP_URLBACKENDLANGUAGE || "",
  LOGIN_URL: process.env.REACT_APP_VARIAMOS_LOGIN_URL || "",
};
